services:
  frontend:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules  # Prevents host's empty node_modules from overwriting container's
    ports:
      - "8080:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable file watching in Docker
    command: npm run dev