services:
  backend:
    build: .
    volumes:
      - .:/usr/src/backend
    ports:
      - "5000:5000"
    environment:
      - ENV=development
    depends_on:
      db:
        condition: service_healthy

    command: flask --app backend.app run --port=5000 --host=0.0.0.0 --debug

  db:  # New PostgreSQL service
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asd
      - POSTGRES_DB=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./data:/var/lib/postgresql/data  # Persists data in ./db
      # - ./db/SQL/initdb:/docker-entrypoint-initdb.d # initialization sql
    ports:
      - "5432:5432"  # Exposes PostgreSQL port
